# Example cubes
AS = [
    Cube("[LBD] LD FR DB BL FU RB RD UR DF UL UB FL LBD DBR BUR RFD LDF FUL BLU UFR")
    Cube("[LUB] FL BR RF DF UF LB UL DR DB RU UB LD FLD BUR RUF LBD FDR UBL BRD ULF")
    Cube("[LDF] UL RU LD BD DR RB BU FR LB DF FU LF UFR BLU FUL URB BRD FLD RFD DLB")
    Cube("[DLB] UR DL DF DR BR BD FR UF LU LF BU BL URB BRD LBD FUL DRF FLD FRU UBL")
    Cube("[UFR] DR LB UF RF FD BR LU BD UB DL RU FL FLD LUB FRU RFD RBU LFU RDB DLB")
]
BS = [
    Cube("[LBD] FL LB BD RU LU UB DR DF FU RF DL BR ULF LUB FLD FRU FDR DLB BUR BRD")
    Cube("[UFR] RU BU LD DR DB UF FR LB RB DF LF UL DFL RDB RUF LBD LUB DRF RBU LFU")
    Cube("[LBD] LB LU RF BD BR DL RD FU UR FD BU FL BLU RFD LBD BUR DBR ULF FRU DFL")
    Cube("[LDF] BU LB DL RF LU RD UR RB FD BD FU LF FUL UFR LBD BLU DBR LDF RFD BUR")
    Cube("[FLD] LU UB LD RF BD DR RB UF BL UR FD FL ULF BRD URB BDL UFR DFL DRF UBL")
]
CS = [
    Cube("[UFR] UL LF DR RF LB DB RB FU DL FD UR UB RFD RBU ULF BDL FLD BLU RDB FRU")
    Cube("[LUB] RB FR RD LB UL FL DB DL BU UF UR DF UBL FUL DFL RDB FRU FDR URB BDL")
    Cube("[BUR] FL DB BL UB FU FR BR LU RU RD DL DF ULF RDB FDR UBL DLB URB FRU FLD")
    Cube("[FUL] FD LB UF UL RD DB DL UB RB RF RU FL LFU URB RUF BDL UBL DFL RFD DBR")
    Cube("[FLD] FR UF DB BU UL BR UR DR FL LB DF DL RFD LBD LUB BRD FLD LFU RBU FRU")
]
DS = [
    Cube("[UFR] FD FU DR BR LF LD BU LB LU RU BD RF URB BRD BLU DRF BDL UFR LDF ULF")
    Cube("[LUB] DF LF BR DB RU LU DR UF FR UB LD BL RFD BRD LDF BUR BLU RUF FUL LBD")
    Cube("[URB] BD UL UF DR DL UB FR UR LF BR BL DF BLU BDL RBU RFD FLD LFU BRD FRU")
    Cube("[RBU] LB RB LU RD FU RU FD BU FR DB LD LF UFR URB FDR UBL DBR DFL ULF LBD")
    Cube("[FLD] DR LF LU LB DB FD FR BR LD UF BU UR FLD BUR LFU FRU RDB DLB LUB DRF")
]
IS = [
    Cube("[LBD] FD DL BR FL FR BD UB FU UR BL RD UL DBR BLU BDL FLD FUL RFD RUF URB")
    Cube("[FLD] DF LF BR DB UL DL FR LB BU UF UR RD BLU RBU DFL DBR RFD RUF FUL BDL")
    Cube("[BRD] RB RU BD UF FL DF LU BU DL LB RD RF UFR ULF BUR BLU BDL LDF DBR FDR")
    Cube("[DLB] DL UF RB RF UB UL RD UR DB LF DF BL BDL UFR DBR LFU DRF LDF LUB BUR")
    Cube("[UFR] UB RB FR BD FD UF LD FL LU BL DR RU LUB FDR RBU LDF FUL RUF DBR LBD")
]
A2S = [
    Cube("[UFR] RU DF RD FL DL BU BR FR FU BL DB UL LUB UFR RDB DFL LFU DRF URB LBD")
    Cube("[FLD] RU UB BD UF FL DL DF LB UL RB RF RD BLU RBU DFL RDB RFD RUF LFU LBD")
    Cube("[BRD] BD UR RF UB RB UF DL LB FL DR LU FD UFR ULF BUR BLU LBD LDF RDB RFD")
    Cube("[UFR] DL UF BR BD BU RF LU UR RD FL FD BL BRD BLU RUF LFU DRF LDF RBU LBD")
    Cube("[UFR] BR LF DR BU DF RU FR UL UF BD BL DL FUL UFR LDF BUR UBL FDR BDL RDB")
]
A3S = [
    Cube("[LBD] RF FU BR UL UR BD UB DF DL FL RD BL RBU LBD RUF FUL FDR LDF DBR LUB")
    Cube("[UFR] RB RF LU FL RU DR UF DL DF BU BD BL UFR URB UBL FUL DRF DFL BDL RDB")
    Cube("[UFR] UB RU BL LD UF UL FR FL DF RB DB RD UFR URB UBL ULF FDR DFL BDL RDB")
    Cube("[DLB] UF UR BU RF FD UL RD DL DB LF RB BL BLU BDL BUR ULF DRF DFL RDB RUF")
    Cube("[UFR] RU LD BR FU FD BL UB RF DR UL FL BD DRF FLD ULF BLU FRU URB BRD BDL")
]
A11S = [
    Cube("[LBD] LD FR BR FL FU BD UB UR DF BL RD UL DLB RDB RBU DFL LFU DRF UBL RUF")
    Cube("[FLD] RU UB BD UF FL DL DF LB UL RB RF RD BLU RBU DFL RDB RFD RUF LFU LBD")
    Cube("[BRD] FU RU BU LU FD RD BD LD RF LF RB LB UFR ULF BUR BLU LBD LDF RDB RFD")
    Cube("[DLB] DL UF RB RF UB UL RD UR DB LF DF BL URB BRD LBD LFU DRF LDF FRU UBL")
    Cube("[UFR] FU RU BU LU FD RD BD LD RF LF RB LB BLU RFD URB FLD LFU FRU DBR LBD")
]
RS = [
    Cube("[UFL] LF LB LU RU BU RF FD BR BD DR DL UF RUB FRD LUF LBU BDR RFU DLF DBL")
    Cube("[DLB] FR UB LU LD LF DB FU RU BR DF LB DR RBU LFU DBR UFR LDF DLB BLU RFD")
    Cube("[UFL] FU DL LF UB LB LU DF RD UR BR DB RF ULB UFL DFR LDB FUR DRB LFD BRU")
    Cube("[BUL] DB UL LD UB FU FL RD LB BR FR UR DF RDF BRU RBD LBU DLF RFU DBL UFL")
    Cube("[URB] LB UF RF DR BR LU BD FD UR BU LF LD LUB FRU RFD FLD DLB RBU LFU RDB")
]

# Trigger sequences
SEXY_MOVE = seq"R U R' U'"
REVERSED_SEXY = seq"U R U' R'"
MIRRORED_SEXY = seq"L' U' L U"
REVERSED_MIRRORED_SEXY = seq"U' L' U L"
SLEDGEHAMMER = seq"R' F R F'"
HEDGEHAMMER = seq"F R' F' R"
CIRCLE = seq"R U R' U"
ANTI_CIRCLE = seq"R U' R' U'"

# PLL sequences
PLL_H = seq"M2 U M2 U2 M2 U M2"
PLL_Z = seq"M' U M2 U M2 U M' U2 M2"
PLL_Ua = seq"M2 U M U2 M' U M2"
PLL_Ub = seq"M2 U' M U2 M' U' M2"

PLL_T = seq"R U R' U' R' F R2 U' R' U' R U R' F'"
PLL_F = seq"R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R"
PLL_Ja = seq"x R2 F R F' R U2 r' U r U2 x'"
PLL_Jb = seq"R U R' F' R U R' U' R' F R2 U' R'"
PLL_Ra = seq"R U' R' U' R U R D R' U' R D' R' U2 R'"
PLL_Rb = seq"R2 F R U R U' R' F' R U2 R' U2 R"
PLL_Ga = seq"R2 U R' U R' U' R U' R2 U' D R' U R D'"
PLL_Gb = seq"R' U' R U D' R2 U R' U R U' R U' R2 D"
PLL_Gc = seq"R2 U' R U' R U R' U R2 U D' R U' R' D"
PLL_Gd = seq"R U R' U' D R2 U' R U' R' U R' U R2 D'"
PLL_Aa = seq"x L2 D2 L' U' L D2 L' U L' x'"
PLL_Ab = seq"x' L2 D2 L U L' D2 L U' L x"

PLL_E = seq"x' L' U L D' L' U' L D L' U' L D' L' U L D x"
PLL_Na = seq"R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'"
PLL_Nb = seq"R' U R U' R' F' U' F R U R' F R' F' R U' R"
PLL_V = seq"R' U R' U' y R' F' R2 U' R' U R' F R F y'"
PLL_Y = seq"F R U' R' U' R U R' F' R U R' U' R' F R F'"
